import { JetBrains_Mono } from 'next/font/google';

import Header from '@/components/header';

import './globals.css';
import PageTransition from '@/components/page-transition';
import StairTransition from '@/components/stair-transition';

const jetBrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  weights: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-jetbrainsMono',
});

export const metadata = {
  title: 'Tolunay Tezcan Portfolio Site',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={jetBrainsMono.variable}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
